name: cultural_analytics
channels:
  - conda-forge
dependencies:
  - python=3.14.2
  - pandas=3.0.0
  - numpy=2.3.5
  - scikit-learn=1.8.0
  - nltk=3.9.4
  - pillow=12.1.0
  - opencv=4.13.0
  - plotly=6.5.2
  - matplotlib=3.10.8
  - jupyter
  - jupyterlab
  - ipykernel
  - pip=25.3

  - pip:
      - wordcloud==1.9.6
      - kaleido==1.2.0
      - mediapipe==0.10.33
      - librosa==0.10.2